@echo OFF
echo Listing %3 (left side)...
ls -Rhl %1 | grep "^[^d][rw-]\{3\}" > %3-l.log
echo Listing %3 (right side)...
ls -Rhl %2 | grep "^[^d][rw-]\{3\}" > %3-r.log
echo Merging...
TortoiseMerge %3-l.log %3-r.log